FROM telegraf:1.35-alpine@sha256:f406ae5d669a91f2ce4fd0ae8ea479dd883760e55e40deb31360af30ce777c36

RUN apk add --quiet --no-cache \
  sudo mtr lm-sensors smartmontools ipmitool nvme-cli && \
  echo 'telegraf ALL=NOPASSWD:/usr/sbin/smartctl *' | tee    /etc/sudoers.d/telegraf && \
  echo 'telegraf ALL=NOPASSWD:/usr/sbin/nvme *'     | tee -a /etc/sudoers.d/telegraf && \
  echo 'telegraf ALL=NOPASSWD:/usr/bin/ipmitool *'  | tee -a /etc/sudoers.d/telegraf && \
  echo "Alpine done."

LABEL org.opencontainers.image.source="https://github.com/influxdata/telegraf" \
  org.opencontainers.image.url="https://github.com/golift/telegraf-docker"
