FROM telegraf:1.38-alpine@sha256:49fc4b3e60115966979d653e76874bd960acdd27cd484a4a57813132e474d882

RUN apk add --quiet --no-cache \
  sudo mtr lm-sensors smartmontools ipmitool nvme-cli && \
  echo 'telegraf ALL=NOPASSWD:/usr/sbin/smartctl *' | tee    /etc/sudoers.d/telegraf && \
  echo 'telegraf ALL=NOPASSWD:/usr/sbin/nvme *'     | tee -a /etc/sudoers.d/telegraf && \
  echo 'telegraf ALL=NOPASSWD:/usr/bin/ipmitool *'  | tee -a /etc/sudoers.d/telegraf && \
  echo "Alpine done."

LABEL org.opencontainers.image.source="https://github.com/influxdata/telegraf" \
  org.opencontainers.image.url="https://github.com/golift/telegraf-docker"
