#!/usr/bin/env bash

PLAT="linux/amd64,linux/arm64/v8,linux/arm/v7"
[ "${DOCKERFILE_PATH}" = "Dockerfile" ] || PLAT="linux/amd64,linux/arm64/v8"

echo "Pushing ${IMAGE_NAME} with platforms: ${PLAT}"

docker buildx build --push --file "${DOCKERFILE_PATH}" --tag "${IMAGE_NAME}" --platform "${PLAT}" .
