#!/usr/bin/env bash

docker buildx build --push --tag "${IMAGE_NAME}" --platform linux/amd64,linux/arm64/v8,linux/arm/v7 .
docker buildx build --push --tag "${IMAGE_NAME}-alpine" --platform linux/amd64,linux/arm64/v8,linux/arm/v7 .
